language: php

php:
    - 7.3

env:
    global:
        - COVERAGE=no
    matrix:
        - LARAVEL=6.8.*
        - LARAVEL=7.0.*
        - LARAVEL=8.0.*

matrix:
    include:
        - php: 7.2
          env: LARAVEL=6.19.* COVERAGE=yes
        - php: 7.2
          env: LARAVEL=7.30.* COVERAGE=yes
        - php: 7.3
          env: LARAVEL=8.5.* COVERAGE=yes
        - php: 7.3
          env: LARAVEL=8.0.* COVERAGE=yes
        - php: 7.2
          env: LARAVEL=6.8.* COVERAGE=yes
        - php: 7.2
          env: LARAVEL=7.0.* COVERAGE=yes
    fast_finish: true

before_install:
    - travis_retry composer self-update

before_script:
    - composer require "laravel/framework=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest

script:
    - if [[ $COVERAGE = 'yes' ]]; then vendor/bin/phpunit --coverage-clover=coverage.xml; fi
    - if [[ $COVERAGE = 'no' ]]; then vendor/bin/phpunit; fi

before_install:
    - pip install --user codecov

after_success:
    - if [[ $COVERAGE = 'yes' ]]; then codecov; fi
